<?php


use Drupal\myroute_noindex\Entity\MyrouteNoindex;


/**
 * Implements hook_preprocess_html().
 * @param $variables
 */
function myroute_noindex_preprocess_html(&$variables) {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();
  if ($route_name && $myroute_noindex_id = \Drupal::service('myroute_noindex.myroute_noindex_evaluator')
      ->evaluateByRouteName($route_name)
  ) {
    /** @var \Drupal\myroute_noindex\Entity\MyrouteNoindex $myroute_noindex */
    $myroute_noindex = MyrouteNoindex::load($myroute_noindex_id);
    $items = $myroute_noindex->getItems();
    if (!empty($items['noindex_type'])) {
      $robots = [
        '#tag' => 'meta',
        '#attributes' => [
          'name' => 'robots',
          'content' => $items['noindex_type'],
        ],
      ];
      $variables['#attached']['html_head'][] = [$robots, 'robots'];
    }
  }
}



